base:
  name: 徐聪
  email: xuerzong@gmail.com
  phone: 18500950299
  github: xuerzong

introduction:
  summary: 我是一名计算机专业本科毕业生、前端工程师。我：
  highlights:
    - 具有很强的学习能力和独立思考能力
    - 善于通过Github、Youtube等平台探索前沿技术，并将其运用于实践中
    - 热衷于用代码构建创意，用应用丰富生活


education-experience:
  - name: 北京交通大学
    school: 计算机与信息技术学院
    major: 物联网工程
    other: 本科-全日制 # GPA 3.7/4
    start-time: 2017-09-01
    end-time: 2021-06-30

work-experience:
  - company-name: 北京希望在线线上学科培训学校
    start-time: 2023-07-06
    # end-time: 至今
    club: 产品研发部 - 增长前端组
    position: 前端开发工程师
    location: 北京
    # summary: 负责《希望学口算》小程序开发
    projects: 
      - name: 希望学口算（微信小程序）
        highlights:
        # - 使用 Taro(React) + Less技术栈
      - name: 成长体系（H5）

  - company-name: 网易有道信息技术(北京)有限公司
    start-time: 2021-04-06
    end-time: 2023-07-05
    club: 国际广告产品部
    position: 高级前端开发工程师
    location: 北京
    summary: 负责有道广告全球数字营销Saas平台开发、维护及周边建设；担任Code reviewer、2022校招面试官等角色。
    projects:
      - name: YoudaoAds全球数字营销Saas平台
        link: https://youdaoads.com
        highlights:
          - 使用 Next.js(React) + Antd + Less + Redux技术栈
          - 主导项目架构设计以及基础建设
          - i18n双语切换
          - 20+种角色权限管理
          - 将官网首屏全球范围平均加载时间控制在<strong>4s</strong>内，业务主要开展地区平均加载时间控制在<strong>1.8s</strong>内
      - name: PassionArk官网
        link: https://passionark.youdao.com
        highlights:
          - 使用 Next.js(React) + Tailwindcss技术栈
          - 编写创作者们、关于我们、联系我们等页面

  - company-name: 北京爱奇艺科技有限公司
    start-time: 2020-11-11
    end-time: 2021-04-06
    club: 基线研发部
    position: H5前端实习生
    location: 北京
    projects:
      - name: 参与低代码平台开发
      - name: 参与影视活动H5页面开发

project-experiences:
  - name: 个人网站
    link: https://xuerzong.com
    description: 个人博客网站。其中技术栈应用于<strong>Youdaoads新闻</strong>、<strong>PassionArk官网案例</strong>页面。

  - name: 多账号管理Chrome插件
    link: https://github.com/xuerzong/auth-manager
    description: 适用多账号/角色的开发场景，能够快速切换账号/角色，增加开发效率。
    
  - name: ChatGPT国内镜像
    link: https://ninepie.chat
    description: 使用 Next.js + TailwindCSS + HeadlessUI + Prisma + Mysql 技术栈搭建。

professional-skills:
  - 前端：Typescript、Javascript、React、Next、Vue
  - 构建：Webpack、Gulp、Rollup、Vite、Esbuild
  - 后端：Nodejs、Python、Mysql、MongoDB、Prisma、Typeorm
