base:
  name: 徐聪
  email: xuerzong@gmail.com
  phone: 18500950299
  github: xuerzong
  website: xuerzong.com

introduction: 我是一名计算机专业本科毕业生、前端工程师，热衷于用代码构建创意，用应用丰富生活。

education-experience:
  - name: 北京交通大学
    school: 计算机与信息技术学院
    major: 物联网工程
    other: 本科-全日制 # GPA 3.7/4
    start-time: 2017-09-01
    end-time: 2021-06-30

work-experience:
  - company-name: 网易有道信息技术(北京)有限公司
    start-time: 2021-04-06
  # end-time: 至今
    club: 国际广告产品部
    position: 高级前端开发工程师
    location: 北京
    summary: 负责有道广告全球数字营销Saas平台开发、维护及周边建设；担任Code reviewer、2022校招面试官等角色。
    highlights:
      - YoudaoAds全球数字营销Saas平台（https://youdaoads.com）
      - PassionArk官网（https://passionark.youdao.com）

  - company-name: 北京爱奇艺科技有限公司
    start-time: 2020-11-11
    end-time: 2021-04-06
    club: 基线研发部
    position: H5前端实习生
    location: 北京
    highlights:
      - 参与低代码平台开发
      - 参与影视活动H5页面开发

project-experiences:
  - name: 个人网站
    link: https://xuerzong.com
    description: 个人博客网站。其中技术栈应用于<strong>Youdaoads新闻</strong>、<strong>热力方舟官网案例</strong>页面。
    stack: Next.js + Tailwindcss + MDX
  
  - name: 多账号管理Chrome插件
    description: 适用开发过程中的多角色切换场景，增加开发效率。
    stack: React.js + Tailwindcss + Vite 

  - name: 短链应用
    description: 创建短链并统计短链的PV、UV。 
    stack: Next.js + Material UI + prisma + MySQL + trpc

  - name: 简历应用
    description: 动态创建简历应用，可参考(https://www.wondercv.com/)。 
    stack: Next.js + Ant Design + Next Auth + prisma + MySQL


professional-skills:
  - 前端：Typescript、Javascript、React、Next、Vue
  - 构建：Webpack、Gulp、Rollup、Vite、Esbuild
  - 后端：Nodejs、Python、Mysql、MongoDB、Prisma、Typeorm
