base:
  name: 徐聪
  email: xuerzong@gmail.com
  phone: 18500950299
  github: xuerzong
  website: https://xuerzong.com

introduction: 我是一名计算机专业本科毕业生、前端工程师，热衷于用代码构建创意，用应用丰富生活。

education-experience:
  - name: 北京交通大学
    school: 计算机与信息技术学院
    major: 物联网工程
    other: 本科-全日制 # GPA 3.7/4
    start-time: 2017-09-01
    end-time: 2021-06-30

work-experience:
  - company-name: 网易有道信息技术(北京)有限公司
    start-time: 2021-04-06
  # end-time: 至今
    club: 国际广告产品部
    position: 高级前端开发工程师
    location: 北京
    summary: 负责有道广告全球数字营销Saas平台（https://youdaoads.com）开发、维护及周边建设；
    highlights:
      - YoudaoAds官网（Next.js + Typescript + Scss）
      - YoudaoAds全球数字营销Saas平台（Next.js + Typescript + Ant Design + Less）

  - company-name: 北京爱奇艺科技有限公司
    start-time: 2020-11-11
    end-time: 2021-04-06
    club: 基线研发部
    position: H5前端实习生
    location: 北京
    highlights:
      - 参与低代码平台开发（Ant Design + React.js + Typescript）
      - 参与影视活动H5页面开发（Vue2 + Vanilla）

professional-skills:
  - 前端：Typescript、Javascript、React、Next、Vue
  - 构建：Webpack、Gulp、Rollup、Vite
  - 后端：Nodejs、Python、Mysql、MongoDB、Prisma、Typeorm

updated_at: 2023-02-10
